// data/districts.js
// districtsData.js
// shippingZone values:
//   dhaka_city    → Dhaka Inside  (City Corporation থানাগুলো)
//   dhaka_sub     → Dhaka Sub     (Gazipur, Narayanganj, Savar, Keraniganj ইত্যাদি)
//   dhaka_outside → Dhaka Out     (Dhaka Division এর বাকি জেলাগুলো)
//   other_district→ Dhaka Division এর বাইরে সব জেলা

export const districtsData = [
    {
        name: "Dhaka",
        upazilas: [
            // Dhaka Inside — City থানাগুলো (Excel: 'Dhaka Inside')
            { name: "Adabor", shippingZone: "dhaka_city" },
            { name: "Badda", shippingZone: "dhaka_city" },
            { name: "Bangshal", shippingZone: "dhaka_city" },
            { name: "Biman Bandar", shippingZone: "dhaka_city" },
            { name: "Cantonment", shippingZone: "dhaka_city" },
            { name: "Chak Bazar", shippingZone: "dhaka_city" },
            { name: "Dakshinkhan", shippingZone: "dhaka_city" },
            { name: "Darus Salam", shippingZone: "dhaka_city" },
            { name: "Demra", shippingZone: "dhaka_city" },
            { name: "Dhanmondi", shippingZone: "dhaka_city" },
            { name: "Gendaria", shippingZone: "dhaka_city" },
            { name: "Gulshan", shippingZone: "dhaka_city" },
            { name: "Hazaribagh", shippingZone: "dhaka_city" },
            { name: "Jatrabari", shippingZone: "dhaka_city" },
            { name: "Kadamtali", shippingZone: "dhaka_city" },
            { name: "Kafrul", shippingZone: "dhaka_city" },
            { name: "Kalabagan", shippingZone: "dhaka_city" },
            { name: "Khilgaon", shippingZone: "dhaka_city" },
            { name: "Khilkhet", shippingZone: "dhaka_city" },
            { name: "Kotwali", shippingZone: "dhaka_city" },
            { name: "Lalbagh", shippingZone: "dhaka_city" },
            { name: "Mirpur", shippingZone: "dhaka_city" },
            { name: "Mohammadpur", shippingZone: "dhaka_city" },
            { name: "Motijheel", shippingZone: "dhaka_city" },
            { name: "Nawabganj", shippingZone: "dhaka_city" },
            { name: "New Market", shippingZone: "dhaka_city" },
            { name: "Pallabi", shippingZone: "dhaka_city" },
            { name: "Paltan", shippingZone: "dhaka_city" },
            { name: "Ramna", shippingZone: "dhaka_city" },
            { name: "Rampura", shippingZone: "dhaka_city" },
            { name: "Sabujbagh", shippingZone: "dhaka_city" },
            { name: "Shah Ali", shippingZone: "dhaka_city" },
            { name: "Shahbagh", shippingZone: "dhaka_city" },
            { name: "Sher-e-bangla Nagar", shippingZone: "dhaka_city" },
            { name: "Shyampur", shippingZone: "dhaka_city" },
            { name: "Sutrapur", shippingZone: "dhaka_city" },
            { name: "Tejgaon", shippingZone: "dhaka_city" },
            { name: "Tejgaon Ind. Area", shippingZone: "dhaka_city" },
            { name: "Turag", shippingZone: "dhaka_city" },
            { name: "Uttar Khan", shippingZone: "dhaka_city" },
            { name: "Uttara", shippingZone: "dhaka_city" },
            // Dhaka Sub — Excel: 'Dhaka Sub'
            { name: "Dhamrai", shippingZone: "dhaka_sub" },
            { name: "Dohar", shippingZone: "dhaka_sub" },
            { name: "Kamrangir Char", shippingZone: "dhaka_sub" },
            { name: "Keraniganj", shippingZone: "dhaka_sub" },
            { name: "Savar", shippingZone: "dhaka_sub" },
        ],
    },
    {
        name: "Gazipur",
        upazilas: [
            // Excel: 'Dhaka Sub'
            { name: "Gazipur Sadar", shippingZone: "dhaka_sub" },
            { name: "Kaliakair", shippingZone: "dhaka_sub" },
            { name: "Kaliganj", shippingZone: "dhaka_sub" },
            { name: "Kapasia", shippingZone: "dhaka_sub" },
            { name: "Sreepur", shippingZone: "dhaka_sub" },
        ],
    },
    {
        name: "Narayanganj",
        upazilas: [
            // Excel: 'Dhaka Sub'
            { name: "Araihazar", shippingZone: "dhaka_sub" },
            { name: "Bandar", shippingZone: "dhaka_sub" },
            { name: "Narayanganj Sadar", shippingZone: "dhaka_sub" },
            { name: "Rupganj", shippingZone: "dhaka_sub" },
            { name: "Sonargaon", shippingZone: "dhaka_sub" },
        ],
    },
    {
        name: "Munshiganj",
        upazilas: [
            // Excel: 'Dhaka out'
            { name: "Gazaria", shippingZone: "dhaka_outside" },
            { name: "Lohajang", shippingZone: "dhaka_outside" },
            { name: "Munshiganj Sadar", shippingZone: "dhaka_outside" },
            { name: "Serajdikhan", shippingZone: "dhaka_outside" },
            { name: "Sreenagar", shippingZone: "dhaka_outside" },
            { name: "Tongibari", shippingZone: "dhaka_outside" },
        ],
    },
    {
        name: "Manikganj",
        upazilas: [
            { name: "Daulatpur", shippingZone: "dhaka_outside" },
            { name: "Ghior", shippingZone: "dhaka_outside" },
            { name: "Harirampur", shippingZone: "dhaka_outside" },
            { name: "Manikganj Sadar", shippingZone: "dhaka_outside" },
            { name: "Saturia", shippingZone: "dhaka_outside" },
            { name: "Shibalaya", shippingZone: "dhaka_outside" },
            { name: "Singair", shippingZone: "dhaka_outside" },
        ],
    },
    {
        name: "Narsingdi",
        upazilas: [
            { name: "Belabo", shippingZone: "dhaka_outside" },
            { name: "Manohardi", shippingZone: "dhaka_outside" },
            { name: "Narsingdi Sadar", shippingZone: "dhaka_outside" },
            { name: "Palash", shippingZone: "dhaka_outside" },
            { name: "Roypura", shippingZone: "dhaka_outside" },
            { name: "Shibpur", shippingZone: "dhaka_outside" },
        ],
    },
    {
        name: "Tangail",
        upazilas: [
            { name: "Basail", shippingZone: "dhaka_outside" },
            { name: "Bhuapur", shippingZone: "dhaka_outside" },
            { name: "Delduar", shippingZone: "dhaka_outside" },
            { name: "Dhanbari", shippingZone: "dhaka_outside" },
            { name: "Ghatail", shippingZone: "dhaka_outside" },
            { name: "Gopalpur", shippingZone: "dhaka_outside" },
            { name: "Kalihati", shippingZone: "dhaka_outside" },
            { name: "Madhupur", shippingZone: "dhaka_outside" },
            { name: "Mirzapur", shippingZone: "dhaka_outside" },
            { name: "Nagarpur", shippingZone: "dhaka_outside" },
            { name: "Sakhipur", shippingZone: "dhaka_outside" },
            { name: "Tangail Sadar", shippingZone: "dhaka_outside" },
        ],
    },
    {
        name: "Kishoreganj",
        upazilas: [
            { name: "Austagram", shippingZone: "dhaka_outside" },
            { name: "Bajitpur", shippingZone: "dhaka_outside" },
            { name: "Bhairab", shippingZone: "dhaka_outside" },
            { name: "Hossainpur", shippingZone: "dhaka_outside" },
            { name: "Itna", shippingZone: "dhaka_outside" },
            { name: "Karimganj", shippingZone: "dhaka_outside" },
            { name: "Katiadi", shippingZone: "dhaka_outside" },
            { name: "Kishoreganj Sadar", shippingZone: "dhaka_outside" },
            { name: "Kuliar Char", shippingZone: "dhaka_outside" },
            { name: "Mithamain", shippingZone: "dhaka_outside" },
            { name: "Nikli", shippingZone: "dhaka_outside" },
            { name: "Pakundia", shippingZone: "dhaka_outside" },
            { name: "Tarail", shippingZone: "dhaka_outside" },
        ],
    },
    {
        name: "Faridpur",
        upazilas: [
            { name: "Alfadanga", shippingZone: "dhaka_outside" },
            { name: "Bhanga", shippingZone: "dhaka_outside" },
            { name: "Boalmari", shippingZone: "dhaka_outside" },
            { name: "Char Bhadrasan", shippingZone: "dhaka_outside" },
            { name: "Faridpur Sadar", shippingZone: "dhaka_outside" },
            { name: "Madhukhali", shippingZone: "dhaka_outside" },
            { name: "Nagarkanda", shippingZone: "dhaka_outside" },
            { name: "Sadarpur", shippingZone: "dhaka_outside" },
            { name: "Saltha", shippingZone: "dhaka_outside" },
        ],
    },
    {
        name: "Gopalganj",
        upazilas: [
            { name: "Gopalganj Sadar", shippingZone: "dhaka_outside" },
            { name: "Kashiani", shippingZone: "dhaka_outside" },
            { name: "Kotali Para", shippingZone: "dhaka_outside" },
            { name: "Muksudpur", shippingZone: "dhaka_outside" },
            { name: "Tungi Para", shippingZone: "dhaka_outside" },
        ],
    },
    {
        name: "Madaripur",
        upazilas: [
            { name: "Kalkini", shippingZone: "dhaka_outside" },
            { name: "Madaripur Sadar", shippingZone: "dhaka_outside" },
            { name: "Rajoir", shippingZone: "dhaka_outside" },
            { name: "Shib Char", shippingZone: "dhaka_outside" },
        ],
    },
    {
        name: "Shariatpur",
        upazilas: [
            { name: "Bhedarganj", shippingZone: "dhaka_outside" },
            { name: "Damudya", shippingZone: "dhaka_outside" },
            { name: "Gosairhat", shippingZone: "dhaka_outside" },
            { name: "Naria", shippingZone: "dhaka_outside" },
            { name: "Shariatpur Sadar", shippingZone: "dhaka_outside" },
            { name: "Zanjira", shippingZone: "dhaka_outside" },
        ],
    },
    {
        name: "Rajbari",
        upazilas: [
            { name: "Balia Kandi", shippingZone: "dhaka_outside" },
            { name: "Goalandaghat", shippingZone: "dhaka_outside" },
            { name: "Kalukhali", shippingZone: "dhaka_outside" },
            { name: "Pangsha", shippingZone: "dhaka_outside" },
            { name: "Rajbari Sadar", shippingZone: "dhaka_outside" },
        ],
    },
    // ── বাকি সব Division এর জেলা (other_district) ──────────────────────────
    {
        name: "Chattogram",
        upazilas: [
            { name: "Anwara", shippingZone: "other_district" },
            { name: "Banshkhali", shippingZone: "other_district" },
            { name: "Boalkhali", shippingZone: "other_district" },
            { name: "Chandanaish", shippingZone: "other_district" },
            { name: "Chattogram City Corporation", shippingZone: "other_district" },
            { name: "Fatikchhari", shippingZone: "other_district" },
            { name: "Hathazari", shippingZone: "other_district" },
            { name: "Lohagara", shippingZone: "other_district" },
            { name: "Mirsharai", shippingZone: "other_district" },
            { name: "Patiya", shippingZone: "other_district" },
            { name: "Rangunia", shippingZone: "other_district" },
            { name: "Raozan", shippingZone: "other_district" },
            { name: "Sandwip", shippingZone: "other_district" },
            { name: "Satkania", shippingZone: "other_district" },
            { name: "Sitakunda", shippingZone: "other_district" },
        ],
    },
    {
        name: "Cox's Bazar",
        upazilas: [
            { name: "Chakaria", shippingZone: "other_district" },
            { name: "Cox's Bazar Sadar", shippingZone: "other_district" },
            { name: "Kutubdia", shippingZone: "other_district" },
            { name: "Maheshkhali", shippingZone: "other_district" },
            { name: "Ramu", shippingZone: "other_district" },
            { name: "Teknaf", shippingZone: "other_district" },
            { name: "Ukhia", shippingZone: "other_district" },
            { name: "Pekua", shippingZone: "other_district" },
        ],
    },
    {
        name: "Khagrachhari",
        upazilas: [
            { name: "Dighinala", shippingZone: "other_district" },
            { name: "Khagrachhari Sadar", shippingZone: "other_district" },
            { name: "Lakshmichhari", shippingZone: "other_district" },
            { name: "Mahalchhari", shippingZone: "other_district" },
            { name: "Manikchhari", shippingZone: "other_district" },
            { name: "Matiranga", shippingZone: "other_district" },
            { name: "Panchhari", shippingZone: "other_district" },
            { name: "Ramgarh", shippingZone: "other_district" },
        ],
    },
    {
        name: "Rangamati",
        upazilas: [
            { name: "Baghaichhari", shippingZone: "other_district" },
            { name: "Barkal", shippingZone: "other_district" },
            { name: "Belaichhari", shippingZone: "other_district" },
            { name: "Juraichhari", shippingZone: "other_district" },
            { name: "Kaptai", shippingZone: "other_district" },
            { name: "Kawkhali", shippingZone: "other_district" },
            { name: "Langadu", shippingZone: "other_district" },
            { name: "Naniarchar", shippingZone: "other_district" },
            { name: "Rajasthali", shippingZone: "other_district" },
            { name: "Rangamati Sadar", shippingZone: "other_district" },
        ],
    },
    {
        name: "Bandarban",
        upazilas: [
            { name: "Ali Kadam", shippingZone: "other_district" },
            { name: "Bandarban Sadar", shippingZone: "other_district" },
            { name: "Lama", shippingZone: "other_district" },
            { name: "Naikhongchhari", shippingZone: "other_district" },
            { name: "Rowangchhari", shippingZone: "other_district" },
            { name: "Ruma", shippingZone: "other_district" },
            { name: "Thanchi", shippingZone: "other_district" },
        ],
    },
    {
        name: "Rajshahi",
        upazilas: [
            { name: "Bagha", shippingZone: "other_district" },
            { name: "Bagmara", shippingZone: "other_district" },
            { name: "Charghat", shippingZone: "other_district" },
            { name: "Durgapur", shippingZone: "other_district" },
            { name: "Godagari", shippingZone: "other_district" },
            { name: "Mohanpur", shippingZone: "other_district" },
            { name: "Paba", shippingZone: "other_district" },
            { name: "Puthia", shippingZone: "other_district" },
            { name: "Rajshahi City", shippingZone: "other_district" },
            { name: "Tanore", shippingZone: "other_district" },
        ],
    },
    {
        name: "Khulna",
        upazilas: [
            { name: "Batiaghata", shippingZone: "other_district" },
            { name: "Dacope", shippingZone: "other_district" },
            { name: "Dumuria", shippingZone: "other_district" },
            { name: "Dighalia", shippingZone: "other_district" },
            { name: "Koyra", shippingZone: "other_district" },
            { name: "Paikgachha", shippingZone: "other_district" },
            { name: "Phultala", shippingZone: "other_district" },
            { name: "Rupsha", shippingZone: "other_district" },
            { name: "Terokhada", shippingZone: "other_district" },
            { name: "Khulna City", shippingZone: "other_district" },
        ],
    },
    {
        name: "Barishal",
        upazilas: [
            { name: "Agailjhara", shippingZone: "other_district" },
            { name: "Babuganj", shippingZone: "other_district" },
            { name: "Bakerganj", shippingZone: "other_district" },
            { name: "Banaripara", shippingZone: "other_district" },
            { name: "Barishal City", shippingZone: "other_district" },
            { name: "Gournadi", shippingZone: "other_district" },
            { name: "Hizla", shippingZone: "other_district" },
            { name: "Mehendiganj", shippingZone: "other_district" },
            { name: "Muladi", shippingZone: "other_district" },
            { name: "Wazirpur", shippingZone: "other_district" },
        ],
    },
    {
        name: "Sylhet",
        upazilas: [
            { name: "Balaganj", shippingZone: "other_district" },
            { name: "Bianibazar", shippingZone: "other_district" },
            { name: "Companiganj", shippingZone: "other_district" },
            { name: "Fenchuganj", shippingZone: "other_district" },
            { name: "Golapganj", shippingZone: "other_district" },
            { name: "Gowainghat", shippingZone: "other_district" },
            { name: "Jaintiapur", shippingZone: "other_district" },
            { name: "Kanaighat", shippingZone: "other_district" },
            { name: "Osmani Nagar", shippingZone: "other_district" },
            { name: "Sylhet City", shippingZone: "other_district" },
            { name: "Zakiganj", shippingZone: "other_district" },
        ],
    },
    {
        name: "Rangpur",
        upazilas: [
            { name: "Badarganj", shippingZone: "other_district" },
            { name: "Gangachara", shippingZone: "other_district" },
            { name: "Kaunia", shippingZone: "other_district" },
            { name: "Mithapukur", shippingZone: "other_district" },
            { name: "Pirgachha", shippingZone: "other_district" },
            { name: "Pirganj", shippingZone: "other_district" },
            { name: "Rangpur City", shippingZone: "other_district" },
            { name: "Taraganj", shippingZone: "other_district" },
        ],
    },
    {
        name: "Mymensingh",
        upazilas: [
            { name: "Bhaluka", shippingZone: "other_district" },
            { name: "Dhobaura", shippingZone: "other_district" },
            { name: "Fulbaria", shippingZone: "other_district" },
            { name: "Gaffargaon", shippingZone: "other_district" },
            { name: "Gauripur", shippingZone: "other_district" },
            { name: "Haluaghat", shippingZone: "other_district" },
            { name: "Ishwarganj", shippingZone: "other_district" },
            { name: "Muktagachha", shippingZone: "other_district" },
            { name: "Mymensingh City", shippingZone: "other_district" },
            { name: "Nandail", shippingZone: "other_district" },
            { name: "Phulpur", shippingZone: "other_district" },
            { name: "Trishal", shippingZone: "other_district" },
        ],
    },
    {
        name: "Cumilla",
        upazilas: [
            { name: "Barura", shippingZone: "other_district" },
            { name: "Brahmanpara", shippingZone: "other_district" },
            { name: "Burichang", shippingZone: "other_district" },
            { name: "Chandina", shippingZone: "other_district" },
            { name: "Chauddagram", shippingZone: "other_district" },
            { name: "Cumilla Sadar", shippingZone: "other_district" },
            { name: "Daudkandi", shippingZone: "other_district" },
            { name: "Debidwar", shippingZone: "other_district" },
            { name: "Homna", shippingZone: "other_district" },
            { name: "Laksam", shippingZone: "other_district" },
            { name: "Manoharganj", shippingZone: "other_district" },
            { name: "Meghna", shippingZone: "other_district" },
            { name: "Muradnagar", shippingZone: "other_district" },
            { name: "Nangalkot", shippingZone: "other_district" },
            { name: "Titas", shippingZone: "other_district" },
        ],
    },
    {
        name: "Jashore",
        upazilas: [
            { name: "Abhaynagar", shippingZone: "other_district" },
            { name: "Bagherpara", shippingZone: "other_district" },
            { name: "Chaugachha", shippingZone: "other_district" },
            { name: "Jashore Sadar", shippingZone: "other_district" },
            { name: "Jhikargachha", shippingZone: "other_district" },
            { name: "Keshabpur", shippingZone: "other_district" },
            { name: "Manirampur", shippingZone: "other_district" },
            { name: "Sharsha", shippingZone: "other_district" },
        ],
    },
    {
        name: "Bogura",
        upazilas: [
            { name: "Adamdighi", shippingZone: "other_district" },
            { name: "Bogura Sadar", shippingZone: "other_district" },
            { name: "Dhunat", shippingZone: "other_district" },
            { name: "Dhupchanchia", shippingZone: "other_district" },
            { name: "Gabtali", shippingZone: "other_district" },
            { name: "Kahaloo", shippingZone: "other_district" },
            { name: "Nandigram", shippingZone: "other_district" },
            { name: "Sariakandi", shippingZone: "other_district" },
            { name: "Shibganj", shippingZone: "other_district" },
            { name: "Sonatala", shippingZone: "other_district" },
        ],
    },
    {
        name: "Pabna",
        upazilas: [
            { name: "Atgharia", shippingZone: "other_district" },
            { name: "Bera", shippingZone: "other_district" },
            { name: "Bhangura", shippingZone: "other_district" },
            { name: "Chatmohar", shippingZone: "other_district" },
            { name: "Faridpur", shippingZone: "other_district" },
            { name: "Ishwardi", shippingZone: "other_district" },
            { name: "Pabna Sadar", shippingZone: "other_district" },
            { name: "Santhia", shippingZone: "other_district" },
            { name: "Sujanagar", shippingZone: "other_district" },
        ],
    },
    {
        name: "Dinajpur",
        upazilas: [
            { name: "Birampur", shippingZone: "other_district" },
            { name: "Birganj", shippingZone: "other_district" },
            { name: "Biral", shippingZone: "other_district" },
            { name: "Bochaganj", shippingZone: "other_district" },
            { name: "Chirirbandar", shippingZone: "other_district" },
            { name: "Dinajpur Sadar", shippingZone: "other_district" },
            { name: "Ghoraghat", shippingZone: "other_district" },
            { name: "Hakimpur", shippingZone: "other_district" },
            { name: "Kaharole", shippingZone: "other_district" },
            { name: "Khansama", shippingZone: "other_district" },
            { name: "Nawabganj", shippingZone: "other_district" },
            { name: "Parbatipur", shippingZone: "other_district" },
            { name: "Phulbari", shippingZone: "other_district" },
        ],
    },
    {
        name: "Satkhira",
        upazilas: [
            { name: "Assasuni", shippingZone: "other_district" },
            { name: "Debhata", shippingZone: "other_district" },
            { name: "Kalaroa", shippingZone: "other_district" },
            { name: "Kaliganj", shippingZone: "other_district" },
            { name: "Satkhira Sadar", shippingZone: "other_district" },
            { name: "Shyamnagar", shippingZone: "other_district" },
            { name: "Tala", shippingZone: "other_district" },
        ],
    },
    {
        name: "Kushtia",
        upazilas: [
            { name: "Bheramara", shippingZone: "other_district" },
            { name: "Daulatpur", shippingZone: "other_district" },
            { name: "Khoksa", shippingZone: "other_district" },
            { name: "Kumarkhali", shippingZone: "other_district" },
            { name: "Kushtia Sadar", shippingZone: "other_district" },
            { name: "Mirpur", shippingZone: "other_district" },
        ],
    },
    {
        name: "Jhenaidah",
        upazilas: [
            { name: "Harinakunda", shippingZone: "other_district" },
            { name: "Jhenaidah Sadar", shippingZone: "other_district" },
            { name: "Kaliganj", shippingZone: "other_district" },
            { name: "Kotchandpur", shippingZone: "other_district" },
            { name: "Maheshpur", shippingZone: "other_district" },
            { name: "Shailkupa", shippingZone: "other_district" },
        ],
    },
    {
        name: "Chuadanga",
        upazilas: [
            { name: "Alamdanga", shippingZone: "other_district" },
            { name: "Chuadanga Sadar", shippingZone: "other_district" },
            { name: "Damurhuda", shippingZone: "other_district" },
            { name: "Jibannagar", shippingZone: "other_district" },
        ],
    },
    {
        name: "Meherpur",
        upazilas: [
            { name: "Gangni", shippingZone: "other_district" },
            { name: "Meherpur Sadar", shippingZone: "other_district" },
            { name: "Mujibnagar", shippingZone: "other_district" },
        ],
    },
    {
        name: "Magura",
        upazilas: [
            { name: "Magura Sadar", shippingZone: "other_district" },
            { name: "Mohammadpur", shippingZone: "other_district" },
            { name: "Shalikha", shippingZone: "other_district" },
            { name: "Sreepur", shippingZone: "other_district" },
        ],
    },
    {
        name: "Pirojpur",
        upazilas: [
            { name: "Bhandaria", shippingZone: "other_district" },
            { name: "Kaukhali", shippingZone: "other_district" },
            { name: "Mathbaria", shippingZone: "other_district" },
            { name: "Nazirpur", shippingZone: "other_district" },
            { name: "Pirojpur Sadar", shippingZone: "other_district" },
            { name: "Nesarabad", shippingZone: "other_district" },
            { name: "Zianagar", shippingZone: "other_district" },
        ],
    },
    {
        name: "Jhalokathi",
        upazilas: [
            { name: "Jhalokathi Sadar", shippingZone: "other_district" },
            { name: "Kathalia", shippingZone: "other_district" },
            { name: "Nalchity", shippingZone: "other_district" },
            { name: "Rajapur", shippingZone: "other_district" },
        ],
    },
    {
        name: "Barguna",
        upazilas: [
            { name: "Amtali", shippingZone: "other_district" },
            { name: "Bamna", shippingZone: "other_district" },
            { name: "Barguna Sadar", shippingZone: "other_district" },
            { name: "Betagi", shippingZone: "other_district" },
            { name: "Patharghata", shippingZone: "other_district" },
            { name: "Taltali", shippingZone: "other_district" },
        ],
    },
    {
        name: "Bhola",
        upazilas: [
            { name: "Bhola Sadar", shippingZone: "other_district" },
            { name: "Burhanuddin", shippingZone: "other_district" },
            { name: "Char Fasson", shippingZone: "other_district" },
            { name: "Daulatkhan", shippingZone: "other_district" },
            { name: "Lalmohan", shippingZone: "other_district" },
            { name: "Manpura", shippingZone: "other_district" },
            { name: "Tazumuddin", shippingZone: "other_district" },
        ],
    },
    {
        name: "Habiganj",
        upazilas: [
            { name: "Ajmiriganj", shippingZone: "other_district" },
            { name: "Bahubal", shippingZone: "other_district" },
            { name: "Baniyachong", shippingZone: "other_district" },
            { name: "Chunarughat", shippingZone: "other_district" },
            { name: "Habiganj Sadar", shippingZone: "other_district" },
            { name: "Lakhai", shippingZone: "other_district" },
            { name: "Madhabpur", shippingZone: "other_district" },
            { name: "Nabiganj", shippingZone: "other_district" },
            { name: "Sayestaganj", shippingZone: "other_district" },
        ],
    },
    {
        name: "Moulvibazar",
        upazilas: [
            { name: "Barlekha", shippingZone: "other_district" },
            { name: "Juri", shippingZone: "other_district" },
            { name: "Kamalganj", shippingZone: "other_district" },
            { name: "Kulaura", shippingZone: "other_district" },
            { name: "Moulvibazar Sadar", shippingZone: "other_district" },
            { name: "Rajnagar", shippingZone: "other_district" },
            { name: "Sreemangal", shippingZone: "other_district" },
        ],
    },
    {
        name: "Sunamganj",
        upazilas: [
            { name: "Bishwamvarpur", shippingZone: "other_district" },
            { name: "Chhatak", shippingZone: "other_district" },
            { name: "Dakshin Sunamganj", shippingZone: "other_district" },
            { name: "Derai", shippingZone: "other_district" },
            { name: "Dharamapasha", shippingZone: "other_district" },
            { name: "Dowarabazar", shippingZone: "other_district" },
            { name: "Jagannathpur", shippingZone: "other_district" },
            { name: "Jamalganj", shippingZone: "other_district" },
            { name: "Sullah", shippingZone: "other_district" },
            { name: "Sunamganj Sadar", shippingZone: "other_district" },
            { name: "Tahirpur", shippingZone: "other_district" },
        ],
    },
    {
        name: "Netrokona",
        upazilas: [
            { name: "Atpara", shippingZone: "other_district" },
            { name: "Barhatta", shippingZone: "other_district" },
            { name: "Durgapur", shippingZone: "other_district" },
            { name: "Kalmakanda", shippingZone: "other_district" },
            { name: "Kendua", shippingZone: "other_district" },
            { name: "Khaliajuri", shippingZone: "other_district" },
            { name: "Madan", shippingZone: "other_district" },
            { name: "Mohanganj", shippingZone: "other_district" },
            { name: "Netrokona Sadar", shippingZone: "other_district" },
            { name: "Purbadhala", shippingZone: "other_district" },
        ],
    },
    {
        name: "Jamalpur",
        upazilas: [
            { name: "Baksiganj", shippingZone: "other_district" },
            { name: "Dewanganj", shippingZone: "other_district" },
            { name: "Islampur", shippingZone: "other_district" },
            { name: "Jamalpur Sadar", shippingZone: "other_district" },
            { name: "Madarganj", shippingZone: "other_district" },
            { name: "Melandaha", shippingZone: "other_district" },
            { name: "Sarishabari", shippingZone: "other_district" },
        ],
    },
    {
        name: "Sherpur",
        upazilas: [
            { name: "Jhenaigati", shippingZone: "other_district" },
            { name: "Nakla", shippingZone: "other_district" },
            { name: "Nalitabari", shippingZone: "other_district" },
            { name: "Sherpur Sadar", shippingZone: "other_district" },
            { name: "Sreebardi", shippingZone: "other_district" },
        ],
    },
    {
        name: "Nilphamari",
        upazilas: [
            { name: "Dimla", shippingZone: "other_district" },
            { name: "Domar", shippingZone: "other_district" },
            { name: "Jaldhaka", shippingZone: "other_district" },
            { name: "Kishoreganj", shippingZone: "other_district" },
            { name: "Nilphamari Sadar", shippingZone: "other_district" },
            { name: "Saidpur", shippingZone: "other_district" },
        ],
    },
    {
        name: "Lalmonirhat",
        upazilas: [
            { name: "Aditmari", shippingZone: "other_district" },
            { name: "Hatibandha", shippingZone: "other_district" },
            { name: "Kaliganj", shippingZone: "other_district" },
            { name: "Lalmonirhat Sadar", shippingZone: "other_district" },
            { name: "Patgram", shippingZone: "other_district" },
        ],
    },
    {
        name: "Kurigram",
        upazilas: [
            { name: "Bhurungamari", shippingZone: "other_district" },
            { name: "Char Rajibpur", shippingZone: "other_district" },
            { name: "Chilmari", shippingZone: "other_district" },
            { name: "Kurigram Sadar", shippingZone: "other_district" },
            { name: "Nageshwari", shippingZone: "other_district" },
            { name: "Phulbari", shippingZone: "other_district" },
            { name: "Rajarhat", shippingZone: "other_district" },
            { name: "Raomari", shippingZone: "other_district" },
            { name: "Ulipur", shippingZone: "other_district" },
        ],
    },
    {
        name: "Gaibandha",
        upazilas: [
            { name: "Fulchhari", shippingZone: "other_district" },
            { name: "Gaibandha Sadar", shippingZone: "other_district" },
            { name: "Gobindaganj", shippingZone: "other_district" },
            { name: "Palashbari", shippingZone: "other_district" },
            { name: "Sadullapur", shippingZone: "other_district" },
            { name: "Sundarganj", shippingZone: "other_district" },
            { name: "Saghata", shippingZone: "other_district" },
        ],
    },
    {
        name: "Thakurgaon",
        upazilas: [
            { name: "Baliadangi", shippingZone: "other_district" },
            { name: "Haripur", shippingZone: "other_district" },
            { name: "Pirganj", shippingZone: "other_district" },
            { name: "Ranisankail", shippingZone: "other_district" },
            { name: "Thakurgaon Sadar", shippingZone: "other_district" },
        ],
    },
    {
        name: "Panchagarh",
        upazilas: [
            { name: "Atwari", shippingZone: "other_district" },
            { name: "Boda", shippingZone: "other_district" },
            { name: "Debiganj", shippingZone: "other_district" },
            { name: "Panchagarh Sadar", shippingZone: "other_district" },
            { name: "Tetulia", shippingZone: "other_district" },
        ],
    },
    {
        name: "Natore",
        upazilas: [
            { name: "Bagatipara", shippingZone: "other_district" },
            { name: "Baraigram", shippingZone: "other_district" },
            { name: "Gurudaspur", shippingZone: "other_district" },
            { name: "Lalpur", shippingZone: "other_district" },
            { name: "Natore Sadar", shippingZone: "other_district" },
            { name: "Singra", shippingZone: "other_district" },
            { name: "Naldanga", shippingZone: "other_district" },
        ],
    },
    {
        name: "Naogaon",
        upazilas: [
            { name: "Atrai", shippingZone: "other_district" },
            { name: "Badalgachhi", shippingZone: "other_district" },
            { name: "Dhamoirhat", shippingZone: "other_district" },
            { name: "Manda", shippingZone: "other_district" },
            { name: "Mohadevpur", shippingZone: "other_district" },
            { name: "Naogaon Sadar", shippingZone: "other_district" },
            { name: "Niamatpur", shippingZone: "other_district" },
            { name: "Patnitala", shippingZone: "other_district" },
            { name: "Porsha", shippingZone: "other_district" },
            { name: "Raninagar", shippingZone: "other_district" },
            { name: "Sapahar", shippingZone: "other_district" },
        ],
    },
    {
        name: "Joypurhat",
        upazilas: [
            { name: "Akkelpur", shippingZone: "other_district" },
            { name: "Joypurhat Sadar", shippingZone: "other_district" },
            { name: "Kalai", shippingZone: "other_district" },
            { name: "Khetlal", shippingZone: "other_district" },
            { name: "Panchbibi", shippingZone: "other_district" },
        ],
    },
    {
        name: "Chapainawabganj",
        upazilas: [
            { name: "Bholahat", shippingZone: "other_district" },
            { name: "Chapainawabganj Sadar", shippingZone: "other_district" },
            { name: "Gomastapur", shippingZone: "other_district" },
            { name: "Nachole", shippingZone: "other_district" },
            { name: "Shibganj", shippingZone: "other_district" },
        ],
    },
    {
        name: "Sirajganj",
        upazilas: [
            { name: "Belkuchi", shippingZone: "other_district" },
            { name: "Chauhali", shippingZone: "other_district" },
            { name: "Kamarkhand", shippingZone: "other_district" },
            { name: "Kazipur", shippingZone: "other_district" },
            { name: "Raiganj", shippingZone: "other_district" },
            { name: "Shahjadpur", shippingZone: "other_district" },
            { name: "Sirajganj Sadar", shippingZone: "other_district" },
            { name: "Tarash", shippingZone: "other_district" },
            { name: "Ullahpara", shippingZone: "other_district" },
        ],
    },
    {
        name: "Noakhali",
        upazilas: [
            { name: "Begumganj", shippingZone: "other_district" },
            { name: "Chatkhil", shippingZone: "other_district" },
            { name: "Companiganj", shippingZone: "other_district" },
            { name: "Hatiya", shippingZone: "other_district" },
            { name: "Kabirhat", shippingZone: "other_district" },
            { name: "Noakhali Sadar", shippingZone: "other_district" },
            { name: "Senbagh", shippingZone: "other_district" },
            { name: "Sonaimuri", shippingZone: "other_district" },
            { name: "Subarnachar", shippingZone: "other_district" },
        ],
    },
    {
        name: "Feni",
        upazilas: [
            { name: "Chhagalnaiya", shippingZone: "other_district" },
            { name: "Daganbhuiyan", shippingZone: "other_district" },
            { name: "Feni Sadar", shippingZone: "other_district" },
            { name: "Fulgazi", shippingZone: "other_district" },
            { name: "Parshuram", shippingZone: "other_district" },
            { name: "Sonagazi", shippingZone: "other_district" },
        ],
    },
    {
        name: "Patuakhali",
        upazilas: [
            { name: "Bauphal", shippingZone: "other_district" },
            { name: "Dashmina", shippingZone: "other_district" },
            { name: "Galachipa", shippingZone: "other_district" },
            { name: "Kalapara", shippingZone: "other_district" },
            { name: "Mirzaganj", shippingZone: "other_district" },
            { name: "Patuakhali Sadar", shippingZone: "other_district" },
            { name: "Rangabali", shippingZone: "other_district" },
            { name: "Dumki", shippingZone: "other_district" },
        ],
    },
    {
        name: "Chandpur",
        upazilas: [
            { name: "Chandpur Sadar", shippingZone: "other_district" },
            { name: "Faridganj", shippingZone: "other_district" },
            { name: "Haimchar", shippingZone: "other_district" },
            { name: "Haziganj", shippingZone: "other_district" },
            { name: "Kachua", shippingZone: "other_district" },
            { name: "Matlab (Dakshin)", shippingZone: "other_district" },
            { name: "Matlab (Uttar)", shippingZone: "other_district" },
            { name: "Shahrasti", shippingZone: "other_district" },
        ],
    },
    {
        name: "Lakshmipur",
        upazilas: [
            { name: "Lakshmipur Sadar", shippingZone: "other_district" },
            { name: "Raipur", shippingZone: "other_district" },
            { name: "Ramganj", shippingZone: "other_district" },
            { name: "Ramgati", shippingZone: "other_district" },
            { name: "Kamalnagar", shippingZone: "other_district" },
        ],
    },
    {
        name: "Brahmanbaria",
        upazilas: [
            { name: "Akhaura", shippingZone: "other_district" },
            { name: "Ashuganj", shippingZone: "other_district" },
            { name: "Bancharampur", shippingZone: "other_district" },
            { name: "Brahmanbaria Sadar", shippingZone: "other_district" },
            { name: "Kasba", shippingZone: "other_district" },
            { name: "Nabinagar", shippingZone: "other_district" },
            { name: "Nasirnagar", shippingZone: "other_district" },
            { name: "Sarail", shippingZone: "other_district" },
            { name: "Bijoynagar", shippingZone: "other_district" },
        ],
    },
];

export const getDistrictsList = () => {
    return districtsData.map((d) => d.name);
};

export const getUpazilasByDistrict = (districtName) => {
    const district = districtsData.find((d) => d.name === districtName);
    return district ? district.upazilas : [];
};
